// flow-typed signature: 84035fedb187b259615d80239be541af
// flow-typed version: <<STUB>>/gitbook-cli_v2.3.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitbook-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitbook-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitbook-cli/bin/gitbook' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/commands' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/config' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/index' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/local' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/registry' {
  declare module.exports: any;
}

declare module 'gitbook-cli/lib/tags' {
  declare module.exports: any;
}

declare module 'gitbook-cli/test/_helper' {
  declare module.exports: any;
}

declare module 'gitbook-cli/test/tags' {
  declare module.exports: any;
}

declare module 'gitbook-cli/test/versions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitbook-cli/bin/gitbook.js' {
  declare module.exports: $Exports<'gitbook-cli/bin/gitbook'>;
}
declare module 'gitbook-cli/lib/commands.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/commands'>;
}
declare module 'gitbook-cli/lib/config.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/config'>;
}
declare module 'gitbook-cli/lib/index.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/index'>;
}
declare module 'gitbook-cli/lib/local.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/local'>;
}
declare module 'gitbook-cli/lib/registry.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/registry'>;
}
declare module 'gitbook-cli/lib/tags.js' {
  declare module.exports: $Exports<'gitbook-cli/lib/tags'>;
}
declare module 'gitbook-cli/test/_helper.js' {
  declare module.exports: $Exports<'gitbook-cli/test/_helper'>;
}
declare module 'gitbook-cli/test/tags.js' {
  declare module.exports: $Exports<'gitbook-cli/test/tags'>;
}
declare module 'gitbook-cli/test/versions.js' {
  declare module.exports: $Exports<'gitbook-cli/test/versions'>;
}
